### ISSUE TITLE
Serieslevel vs studylevel

### ISSUE THREAD

**Issue by tcdewit** [MedPhysQC/CR_Flatfield#2]
Currently this module is configured to run at series level (original wad-qc v1 module at study level). This requires more selectors (one for each detector) and instead of editing 1 metafile, modifications have to be made to multiple metafiles.   
What's the disadvantage of switching to studylevel (and prefixing the results with the protocolname/seriesdescr)?

**Comment by MedPhysQC** [comment]
Now works both at series and study level.
